-- ETF Depot Andreas Version 10.2 Cloud Verified
-- Kann gefahrlos erneut im Supabase SQL Editor ausgeführt werden.

create table if not exists public.portfolio_sync (
  user_id uuid primary key references auth.users(id) on delete cascade,
  portfolio_data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  schema_version text not null default '10.2'
);

alter table public.portfolio_sync
  add column if not exists schema_version text not null default '10.2';

create table if not exists public.portfolio_sync_versions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  portfolio_data jsonb not null,
  reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.portfolio_devices (
  user_id uuid not null references auth.users(id) on delete cascade,
  device_id text not null,
  device_name text,
  last_seen timestamptz not null default now(),
  primary key (user_id, device_id)
);

alter table public.portfolio_sync enable row level security;
alter table public.portfolio_sync_versions enable row level security;
alter table public.portfolio_devices enable row level security;

drop policy if exists "Users read own portfolio" on public.portfolio_sync;
create policy "Users read own portfolio" on public.portfolio_sync for select using (auth.uid() = user_id);
drop policy if exists "Users insert own portfolio" on public.portfolio_sync;
create policy "Users insert own portfolio" on public.portfolio_sync for insert with check (auth.uid() = user_id);
drop policy if exists "Users update own portfolio" on public.portfolio_sync;
create policy "Users update own portfolio" on public.portfolio_sync for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users delete own portfolio" on public.portfolio_sync;
create policy "Users delete own portfolio" on public.portfolio_sync for delete using (auth.uid() = user_id);

drop policy if exists "Users read own portfolio versions" on public.portfolio_sync_versions;
create policy "Users read own portfolio versions" on public.portfolio_sync_versions for select using (auth.uid() = user_id);
drop policy if exists "Users insert own portfolio versions" on public.portfolio_sync_versions;
create policy "Users insert own portfolio versions" on public.portfolio_sync_versions for insert with check (auth.uid() = user_id);
drop policy if exists "Users delete own portfolio versions" on public.portfolio_sync_versions;
create policy "Users delete own portfolio versions" on public.portfolio_sync_versions for delete using (auth.uid() = user_id);

drop policy if exists "Users read own devices" on public.portfolio_devices;
create policy "Users read own devices" on public.portfolio_devices for select using (auth.uid() = user_id);
drop policy if exists "Users insert own devices" on public.portfolio_devices;
create policy "Users insert own devices" on public.portfolio_devices for insert with check (auth.uid() = user_id);
drop policy if exists "Users update own devices" on public.portfolio_devices;
create policy "Users update own devices" on public.portfolio_devices for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users delete own devices" on public.portfolio_devices;
create policy "Users delete own devices" on public.portfolio_devices for delete using (auth.uid() = user_id);

create index if not exists portfolio_sync_versions_user_created_idx
on public.portfolio_sync_versions(user_id, created_at desc);

create index if not exists portfolio_devices_user_seen_idx
on public.portfolio_devices(user_id, last_seen desc);

-- Optional: vorhandene Zeilen werden beim nächsten App-Sync automatisch auf 10.2 gesetzt.
-- Dieser Befehl ist nicht erforderlich:
-- update public.portfolio_sync set schema_version='10.2';
